Fix: add option of use node hostname dns to support edge scene
alibaba/open-local pull request #207
Opened 2023-04-06 07:51 UTC by LaurenceLiZhixin

In the edge computing scenario, we need to go through the cloud edge network proxy to access the specific port of the edge computing node, so I added a start option, `use-node-hostname-dns`, which defaults set to `false`, to enable the grpc call based on the hostname.

After this parameter is enabled, the machine will no longer based on an ip address to dial. Instead, the request for with dial to `${hostName}:${port}` will be made, for example, `my-edge-001-node:1736`. The domain name resolves the dns server configured during deployment to the proxy, which is applicable to the edge computing scenario where the network is visible in one direction.

在边缘计算场景下，我们需要通过云边网络代理，才能访问至边缘计算节点的特定端口，因此我增加了一个启动参数  `use-node-hostname-dns`， 默认为 `false`，用于开启基于主机名的grpc 调用。

启动这一参数后，位于中心侧的 csi-plugin 在建立grpc 链接之前，将不再基于机器ip进行调用，而是直接发起 ${hostName}:${port} 的请求，例如 my-edge-001-node:1736 。域名将被部署至集群时时配置的 dns 服务器解析至代理，从而适配于网络单向可见的边缘计算场景。

2023-04-06 07:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/open-local?pullRequest=207) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/open-local?pullRequest=207) before we can accept your contribution.<br/><hr/>**lizhixin.lzx** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/open-local?pullRequest=207) it.</sub>

2023-04-06 10:57 UTC, TheBeatles1994 commented on pkg/csi/controllerserver.go
> +		addr = node.Name + ":" + server.GetLvmdPort()
这个配置是只在边缘节点生效？其他非边缘节点使用哪个配置呢？

2023-04-06 11:59 UTC, peter-wangxu commented
两个问题： @LaurenceLiZhixin 
1. 这个场景是不是csi controller链接节点 lvmd的优先地址类型？跟apiserver链接kubelet有些类似
>  --kubelet-preferred-address-types strings     默认值：Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP
>  用于 kubelet 连接的首选 NodeAddressTypes 列表。
如果是的话，要扩展性好的话可以参考apiserver类似的实现（是不是跟你们边缘场景更加匹配？）

2. 这个配置看上去是全局一致的，所有边缘节点都使用同样的逻辑链接，是否存在不同的节点使用不同的地址类型？

2023-04-07 01:56 UTC, LaurenceLiZhixin commented on pkg/csi/controllerserver.go
> +		addr = node.Name + ":" + server.GetLvmdPort()
@TheBeatles1994 
这个配置是按需开启的，默认不开启，正常情况下不需要增加这一参数。
在边缘或有特殊要求的场景下，由 openlocal 的用户开启这个参数。

2023-04-07 01:58 UTC, LaurenceLiZhixin commented
> NodeAddressTypes
@peter-wangxu 
1. 第一个问题，你说的对，是这样。
2. 第二个问题，开启这一开关的 csi-plugin ，在我们的场景下是位于中心测的；位于边缘节点的实例无需开启。

2023-04-07 02:29 UTC, TheBeatles1994 commented
> > NodeAddressTypes
> @peter-wangxu 
> 2. 第二个问题，开启这一开关的 csi-plugin ，在我们的场景下是位于中心测的；位于边缘节点的实例无需开启。

Agent是以daemonset方式部署，一个集群同一组件应该只支持一种配置吧？

2023-04-07 04:58 UTC, peter-wangxu requested changes
两个小改动

2023-04-07 04:58 UTC, peter-wangxu commented on pkg/csi/controllerserver.go
> +	if cs.options.useNodeHostDNS {
建议将 option穿到GetNodeAddr中，拼接逻辑就不用写两次了
```golang
fun getNodeAddr(node *v1.Node, useNodeHostname bool, nodeID string) (string, error) { 
...
}
```

2023-04-07 04:58 UTC, peter-wangxu commented on cmd/csi/options.go
> +	fs.BoolVar(&option.UseNodeHostnameDNS, "use-node-hostname-dns", false, "use node hostname dns for grpc connection")
hostname有short和long两种形式，短的形如 `habc`  长的形如`habc.sqa.eu95`

选项可以缩短为 `UseNodeHostname`？

2023-04-07 08:49 UTC, LaurenceLiZhixin commented
> > > NodeAddressTypes
> > > @peter-wangxu
> > 
> > 
> > 
> > 2. 第二个问题，开启这一开关的 csi-plugin ，在我们的场景下是位于中心测的；位于边缘节点的实例无需开启。
> 
> Agent是以daemonset方式部署，一个集群同一组件应该只支持一种配置吧？

是的，我只是在中心侧用到这个参数，边缘侧不做改动。

2023-04-07 08:50 UTC, LaurenceLiZhixin commented on cmd/csi/options.go
> +	fs.BoolVar(&option.UseNodeHostnameDNS, "use-node-hostname-dns", false, "use node hostname dns for grpc connection")
可以的

2023-04-09 14:18 UTC, TheBeatles1994 commented
> 2\. 第二个问题，开启这一开关的 csi-plugin ，在我们的场景下是位于中心测的；位于边缘节点的实例无需开启。

openyurt 支持这种同一集群下同一 daemonset 在边缘节点的 pod 配置与中心侧不同？

2023-04-10 01:26 UTC, LaurenceLiZhixin commented
> 

在 CNStack 的架构中，中心侧的 controller 是 deployment 部署的，并不是ds、我只需要针对deploy yoda-controller -c csi-plugin 这一容器开启参数即可 @TheBeatles1994

2023-04-10 02:18 UTC, peter-wangxu commented
LGTM

2023-04-10 02:38 UTC, TheBeatles1994 commented
备注：边缘场景下，controller调用同一 pod 内的 csi-plugin 容器，该容器使用 node name 去连接对应节点（边缘节点、非边缘节点均可）的 agent。这里边缘组件会提前配置集群的 dns，同时 controller 中的 csi-plugin 容器也会配置 dns 配置。

2023-04-10 02:38 UTC, merged