在大规模场景下，降低agent对apiserver的访问压力
alibaba/open-local pull request #253
Opened 2024-02-20 07:56 UTC by ypnuaa037

【背景问题】
在大规模集群场景下，发现agent对apiserver的压力很大。通过分析发现，主要源于两处：
1. agent会不停的访问apiserver读取NodeLocalStorage，检测spdk配置，间隔只有100ms，因而对apiserver的访问频率 = 10 * N / s（N为节点数）
2. agent会定时上报节点的NodeLocalStorage状态，无论NodeLocalStorage状态是否变化都会上报，上报周期是60s
其中，问题1是主要压力来源

【解决思路】
1. 降低访问频率，不需要100ms这么频繁访问
2. 只在NodeLocalStorage发生变化时才上报，因为大部分时间是没有变化的，不需要上报

2024-02-20 07:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/open-local?pullRequest=253) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/open-local?pullRequest=253) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/open-local?pullRequest=253) it.</sub>

2024-02-21 01:46 UTC, peter-wangxu requested changes
代码增加一个单元testcase

2024-02-21 01:46 UTC, peter-wangxu commented on pkg/csi/nodeserver.go
> +		time.Sleep(time.Second * 60)
如果为60s，增加一块磁盘是不是也要1分钟才能生效？
如果是的话，改成1s也影响不大，毕竟都有差异化diff了

2024-02-21 07:41 UTC, ypnuaa037 commented on pkg/csi/nodeserver.go
> +		time.Sleep(time.Second * 60)
> 如果为60s，增加一块磁盘是不是也要1分钟才能生效？ 如果是的话，改成1s也影响不大，毕竟都有差异化diff了

对大规模集群来说，1s感觉还是有点频繁，而且对于没有使用到spdk的场景来说就是无意义的检测。延长到3-5秒或改成可配置，是否可以？

2024-02-21 07:57 UTC, ypnuaa037 commented on pkg/csi/nodeserver.go
> +		time.Sleep(time.Second * 60)
> 如果为60s，增加一块磁盘是不是也要1分钟才能生效？ 如果是的话，改成1s也影响不大，毕竟都有差异化diff了

在1000节点规模的集群里，我们实测安装agent比不安装要多消耗10个核的cpu，改成1秒理论上也有1核cpu的消耗

2024-02-21 09:59 UTC, peter-wangxu commented on pkg/csi/nodeserver.go
> +		time.Sleep(time.Second * 60)
可以的改成3-5ok的

2024-03-25 12:13 UTC, ypnuaa037 commented on pkg/csi/nodeserver.go
> +		time.Sleep(time.Second * 60)
> 可以的改成3-5ok的

已加单元测试，帮再review下，谢谢

2024-03-26 04:28 UTC, merged