fix: failed to create `striped` lv, after add new PV in VG
alibaba/open-local pull request #6
Opened 2021-09-08 07:57 UTC by tangtx3

fix the issues[#5 ]

2021-09-08 07:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/open-local?pullRequest=6) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/open-local?pullRequest=6) before we can accept your contribution.<br/><hr/>**唐天喜** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/open-local?pullRequest=6) it.</sub>

2021-09-08 12:52 UTC, peter-wangxu requested changes
small nits

2021-09-08 12:52 UTC, peter-wangxu commented on pkg/csi/lib/parser.go
> +// ParsePV parse physical volume
parse -> `parses`

2021-09-08 12:52 UTC, peter-wangxu commented on pkg/csi/server/commands.go
> +	args := []string{localtype.NsenterCmd, "pvs", "--units=b", "--separator=\"<:SEP:>\"", "--nosuffix", "--noheadings",
sparator`<:SEP:>` should use constant

2021-09-09 02:21 UTC, TheBeatles1994 commented on pkg/csi/lib/parser.go
> +	size, err := strconv.ParseUint(fields["LVM2_PV_SIZE"], 10, 64)
Those can also be expressed as a constant: 
- LVM2_PV_NAME
- LVM2_PV_SIZE
- LVM2_PV_UUID
- LVM2_PV_TAGS

2021-09-10 01:49 UTC, TheBeatles1994 commented
/lgtm

2021-09-10 01:49 UTC, merged